### PR TITLE
Custom sounds

### PR DESCRIPTION
**Pull request by cgfischer**
I took a crack at trying to add a <customSound> property and resolve it in the Android Java using a main/res/raw resource name.  Not really familiar with Java or how to test Android specific code with flutter.  Hoping this helps and you can tidy up any mistakes on my part.

### CODE REVIEW

**Comment by stefanschaller** [comment]
@caseyryan  What do you think? I would appreciate the feature in the new release .

**Comment by jtmcdole** [comment]
Kind ping from 2024 :)

**Comment by caseyryan** [comment]
> Kind ping from 2024 :)

Hi. I've merged this and updated flutter / dart restrictions. I haven't cheched it myself though, since I don't use this package anymore. 
The updates are available in version 3.0.0 https://pub.dev/packages/flutter_notification_channel

**Comment by jtmcdole** [comment]
I just tried to compile with it and got:

```
Local\Pub\Cache\hosted\pub.dev\flutter_notification_channel-3.0.0\android\src\main\java\com\softmaestri\notification\channel\flutter_notification_channel\FlutterNotificationChannelPlugin.java:88: error: cannot find symbol
              uri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://"+ getApplicationContext().getPackageName() + "/raw/" + customSound);
                              ^
  symbol:   variable ContentResolver
  location: class FlutterNotificationChannelPlugin
\Pub\Cache\hosted\pub.dev\flutter_notification_channel-3.0.0\android\src\main\java\com\softmaestri\notification\channel\flutter_notification_channel\FlutterNotificationChannelPlugin.java:88: error: cannot find symbol
              uri = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://"+ getApplicationContext().getPackageName() + "/raw/" + customSound);
                                                                               ^
  symbol:   method getApplicationContext()
  location: class FlutterNotificationChannelPlugin
\Local\Pub\Cache\hosted\pub.dev\flutter_notification_channel-3.0.0\android\src\main\java\com\softmaestri\notification\channel\flutter_notification_channel\FlutterNotificationChannelPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
```

**Comment by jtmcdole** [comment]
I'll try to fork and test tomorrow

**Comment by caseyryan** [comment]
> I'll try to fork and test tomorrow

I would appreciate it, since I absolutely have no time to support some of my packages at the moment

**Comment by jtmcdole** [comment]
I tried... but this plugin is fairly old (java, old embedding, etc) and every thing I've done has failed to get it even analyzing in android studio.  The plugin is fairly simple; so I wonder if it's worth a nuke, re-create, and copy over the meat. Thoughts?

**Comment by jtmcdole** [comment]
nuke-it-from-orbit worked. I'll put up a chaunky pull request.

**Comment by caseyryan** [comment]
> I tried... but this plugin is fairly old (java, old embedding, etc) and every thing I've done has failed to get it even analyzing in android studio. The plugin is fairly simple; so I wonder if it's worth a nuke, re-create, and copy over the meat. Thoughts?

Yeah, I think that's the best option. Way better than trying to fix the current solution

**Pull request merged**
